<?php

declare(strict_types=1);

namespace bytesof\formable\migrations;

use bytesof\formable\db\Table;
use bytesof\formable\services\Statuses;
use Craft;
use craft\db\Migration;
use craft\db\Query;

/**
 * Moves the submission statuses an install already has into project config.
 *
 * Statuses used to be seeded by the install migration and never written again -
 * there was no way to add, rename, recolour, reorder or delete one. They are
 * editable now, and project config owns them, so the rows that are already on
 * the table have to become the config those edits are applied to. See
 * internal/decisions/0023-submission-statuses-are-project-config.md.
 *
 * The rows keep their ids and uids: `formable_submissions.statusId` and
 * `formable_forms.defaultStatusId` point at them, and nothing about a stored
 * submission changes here.
 */
final class m260817_000000_statuses_in_project_config extends Migration
{
    public function safeUp(): bool
    {
        $projectConfig = Craft::$app->getProjectConfig();

        // The incoming config's schema version, not this install's: if the
        // config being deployed was generated by a site that has already been
        // through this migration, it carries the statuses and this environment
        // must leave them alone - and must not try to write project config,
        // which is read-only wherever admin changes are locked down.
        $schemaVersion = $projectConfig->get('plugins.formable.schemaVersion', true);

        if ($schemaVersion !== null && version_compare((string)$schemaVersion, '1.8.0', '>=')) {
            return true;
        }

        if ($projectConfig->get(Statuses::CONFIG_KEY) !== null) {
            return true;
        }

        $rows = (new Query())
            ->select(['name', 'handle', 'color', 'sortOrder', 'isDefault', 'uid'])
            ->from([Table::STATUSES])
            ->where(['dateDeleted' => null])
            ->orderBy(['sortOrder' => SORT_ASC, 'id' => SORT_ASC])
            ->all();

        foreach ($rows as $row) {
            $projectConfig->set(
                Statuses::CONFIG_KEY . '.' . $row['uid'],
                [
                    'name' => (string)$row['name'],
                    'handle' => (string)$row['handle'],
                    'color' => (string)$row['color'],
                    'sortOrder' => (int)$row['sortOrder'],
                    'isDefault' => (bool)$row['isDefault'],
                ],
                "Add the “{$row['handle']}” submission status to project config",
            );
        }

        return true;
    }

    public function safeDown(): bool
    {
        // The rows stay - they are what submissions point at. Only the config
        // that now describes them goes.
        Craft::$app->getProjectConfig()->remove(Statuses::CONFIG_KEY);

        return true;
    }
}
